"""rbac audit and decimal money

Revision ID: b8d3db34366b
Revises: 2746d716fce9
Create Date: 2026-08-09 03:51:03.463856
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8d3db34366b'
down_revision: Union[str, Sequence[str], None] = '2746d716fce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('resource', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    with op.batch_alter_table('appointments') as batch_op:
        batch_op.alter_column('price_charged',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tier_discount_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    with op.batch_alter_table('clients') as batch_op:
        batch_op.alter_column('total_spent',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('cost_per_unit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    with op.batch_alter_table('professionals') as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
        batch_op.alter_column('monthly_goal',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    with op.batch_alter_table('services') as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('professional_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_users_professional_id', ['professional_id'])
        batch_op.create_foreign_key('fk_users_professional_id', 'professionals', ['professional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_professional_id', type_='foreignkey')
        batch_op.drop_constraint('uq_users_professional_id', type_='unique')
        batch_op.drop_column('professional_id')
    with op.batch_alter_table('services') as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    with op.batch_alter_table('professionals') as batch_op:
        batch_op.alter_column('monthly_goal',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('commission_rate',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('cost_per_unit',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    with op.batch_alter_table('clients') as batch_op:
        batch_op.alter_column('total_spent',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    with op.batch_alter_table('appointments') as batch_op:
        batch_op.alter_column('tier_discount_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price_charged',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
