"""fiscal_demonstration

Revision ID: e1f2a3b4c5d6
Revises: d9e64a3b2f10
Create Date: 2026-09-15 20:52:09.749616
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1f2a3b4c5d6'
down_revision: Union[str, Sequence[str], None] = 'd9e64a3b2f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_fiscal_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_fiscal_profiles_tenant_id'),
    sa.UniqueConstraint('tenant_id', name='uq_fiscal_profile_tenant')
    )
    op.create_index(op.f('ix_fiscal_profiles_tenant_id'), 'fiscal_profiles', ['tenant_id'], unique=False)
    op.create_table('fiscal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_kind', sa.String(length=16), nullable=False),
    sa.Column('source_key', sa.String(length=160), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=True),
    sa.Column('competence', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('service_code', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iss_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('iss_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issuer', sa.JSON(), nullable=False),
    sa.Column('recipient', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=300), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'appointment_id'], ['appointments.tenant_id', 'appointments.id'], name='fk_fiscal_documents_appointment_id_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_fiscal_documents_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'issuer_kind', 'source_key', name='uq_fiscal_document_source')
    )
    op.create_index(op.f('ix_fiscal_documents_tenant_id'), 'fiscal_documents', ['tenant_id'], unique=False)
    op.create_table('fiscal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['fiscal_documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['fiscal_documents.tenant_id', 'fiscal_documents.id'], name='fk_fiscal_events_document_id_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_fiscal_events_tenant_id')
    )
    op.create_index(op.f('ix_fiscal_events_tenant_id'), 'fiscal_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fiscal_events_tenant_id'), table_name='fiscal_events')
    op.drop_table('fiscal_events')
    op.drop_index(op.f('ix_fiscal_documents_tenant_id'), table_name='fiscal_documents')
    op.drop_table('fiscal_documents')
    op.drop_index(op.f('ix_fiscal_profiles_tenant_id'), table_name='fiscal_profiles')
    op.drop_table('fiscal_profiles')
    op.drop_table('platform_fiscal_profile')
    # ### end Alembic commands ###
